version: "3"
services:
  catalog-service-1:
    image: catalog-service
    container_name: catalog-service-1
    build:
      context: ./catalog-service  
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./catalog-service/catalog.csv:/app/catalog.csv  
    networks:
      - network1

  catalog-service-2:
    image: catalog-service
    container_name: catalog-service-2
    ports:
      - "3002:3001" 
    environment:
      - PORT=3002
    volumes:
      - ./catalog-service/catalog.csv:/app/catalog.csv
    networks:
      - network1

  order-service-1:
    image: order-service
    container_name: order-service-1
    build:
      context: ./order-service  
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    networks:
      - network1
    depends_on:
      - catalog-service-1
      - catalog-service-2

  order-service-2:
    image: order-service
    container_name: order-service-2
    ports:
      - "3004:3003" 
    environment:
      - PORT=3004 
    networks:
      - network1
    depends_on:
      - catalog-service-1
      - catalog-service-2

  frontend-service:
    image: frontend-service
    container_name: frontend-service
    build:
      context: ./frontend
    networks:
      - network1
    depends_on:
      - order-service-1
      - order-service-2
      - catalog-service-1
      - catalog-service-2
    stdin_open: true
    tty: true

networks:
  network1:
    driver: bridge
